//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DateCmd { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<int> idClient { get; set; }
    
        public virtual client client { get; set; }
    }
}
